<div class="bg-ivory-default absolute inset-0 z-100 flex items-center justify-center">
	<div class="justify-center justify-center">
		<svg
			width="100"
			height="100"
			viewBox="0 0 205 205"
			fill="none"
			xmlns="http://www.w3.org/2000/svg"
		>
			<g class="animate-bounce-icon-1">
				<rect
					x="29"
					y="39"
					width="46"
					height="45"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
				<rect
					x="29"
					y="90"
					width="46"
					height="33"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
				<rect
					x="29"
					y="129"
					width="46"
					height="21"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
			</g>
			<g class="animate-bounce-icon-2">
				<rect
					x="79"
					y="46"
					width="46"
					height="26"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
				<rect
					x="79"
					y="77"
					width="46"
					height="46"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
				<rect
					x="79"
					y="129"
					width="46"
					height="41"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
			</g>
			<g class="animate-bounce-icon-3">
				<rect
					x="129"
					y="42"
					width="46"
					height="42"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
				<rect
					x="129"
					y="90"
					width="46"
					height="22"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>

				<rect
					x="129"
					y="118"
					width="46"
					height="33"
					rx="6"
					fill="none"
					stroke="black"
					stroke-width="2"
				/>
			</g>
		</svg>
	</div>
</div>
